[window]
option_as_alt = "Both"
padding.x = 8
padding.y = 8
dimensions.columns = 120
dimensions.lines = 30

[font]
normal.family = "Geist Mono"
size = 13
builtin_box_drawing = false

[cursor]
blink_interval = 500

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

# https://stephango.com/flexoki

[colors.primary]
background = "#FFFCF0"
foreground = "#100F0F"

[colors.normal]
black = "#000000"
red = "#AF3029"
green = "#66800B"
yellow = "#AD8301"
blue = "#205EA6"
magenta = "#A02F6F"
cyan = "#24837B"
white = "#B7B5AC"

[colors.bright]
black = "#575653"
red = "#D14D41"
yellow = "#D0A215"
green = "#879A39"
blue = "#4385BE"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#FFFFFF"
