# Prefix
unbind C-b
set-option -g prefix C-z
bind-key C-z send-prefix

# Terminal Setup
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g extended-keys on
set -g extended-keys-format csi-u
set -as terminal-features "xterm*:extkeys"
set -sg escape-time 0
set -g allow-passthrough on
set -g focus-events on
set -g mouse on

# Numbering/Titles
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1
set -g set-titles on
set -g set-titles-string "#T — #S — #h"

# Style
set -g status-style "bg=gray,fg=black"
set -g status-left-length "100"
set -g status-right ""
set -g window-status-current-style "bold"
set -g pane-border-style "fg=gray"
